version: '3'
services:
  jaqsd:
    container_name: jaqsd
    build: .
    image: jaqsd
    volumes:
      - type: volume
        source: logs
        target: /logs
      - type: volume
        source: conf
        target: /conf
volumes:
  logs:
  conf: