version: '3'
services:
  jaqsd:
    container_name: jaqsd
    build: .
    image: jaqsd
    volumes:
      - "./conf:/conf"
      - ".:/logs"
    environment:
      INIT_LB_DAILY: ""
      INIT_INDICATOR: ""
      SYNC_TABLE: ""
