#mongodb_uri: "mongodb://192.168.0.101,192.168.0.102"
mongodb_uri: "mongodb://localhost:37017"
username: "13823156147"
password: "eyJhbGciOiJIUzI1NiJ9.eyJjcmVhdGVfdGltZSI6IjE1MTI3ODY3ODYxODMiLCJpc3MiOiJhdXRoMCIsImlkIjoiMTM4MjMxNTYxNDcifQ.Lt4orfuPoP5xVM_t3n4SdC7xwPNDoloHdvCAWU4JfYQ"
col_map:
  lb.income: lb.income
  lb.cashFlow: lb.cashFlow
  lb.balanceSheet: lb.balanceSheet
db_map:
  lb.secDailyIndicator: SecDailyIndicator
  future:
    M1: future_1M